"""
Layer 4 — Access Control Policy Engine

Mirrors packages/core/src/access/policy-engine.ts
"""

from __future__ import annotations

import fnmatch
from dataclasses import dataclass
from typing import Literal

from ..config import AccessConfig, AgentTypePolicy
from ..types import AgentContext

PolicyDecision = Literal["allow", "deny", "rate-limit"]

CATEGORY_UA_REPRESENTATIVES: dict[str, list[str]] = {
    "training-crawler": [
        "GPTBot", "ClaudeBot", "Google-Extended", "CCBot",
        "Bytespider", "anthropic-ai", "Meta-ExternalAgent",
        "Amazonbot", "Applebot-Extended", "cohere-ai", "AI2Bot",
    ],
    "search-bot": [
        "OAI-SearchBot", "ChatGPT-User", "PerplexityBot",
        "YouBot", "DuckAssistBot",
    ],
    "interactive-agent": [
        "GoogleAgent-URLContext", "Claude-Web", "Claude-SearchBot",
    ],
}


@dataclass(frozen=True)
class PolicyResult:
    decision: PolicyDecision
    reason: str
    status_code: int | None


_ALLOW = PolicyResult(decision="allow", reason="No matching deny rules", status_code=None)


def _deny(reason: str) -> PolicyResult:
    return PolicyResult(decision="deny", reason=reason, status_code=403)


def _apply_agent_policy(
    policy: AgentTypePolicy,
    path: str,
    allow_patterns: list[str],
) -> PolicyResult | None:
    """Apply a named policy. Returns None to continue evaluation, or a final result."""
    if policy == "deny-all":
        return _deny("Agent type policy: deny-all")
    if policy == "allow-all":
        return None
    if policy == "allow-public":
        if allow_patterns and not any(fnmatch.fnmatch(path, p) for p in allow_patterns):
            return _deny("Agent type policy: allow-public — path not in allow list")
        return None
    return None


def evaluate_policy(context: AgentContext, config: AccessConfig) -> PolicyResult:
    """Evaluate the access policy for an agent request."""
    if not context.is_agent:
        return _ALLOW

    path = context.path
    allow_patterns = config.allow or []

    # 1. Per-operator overrides
    if config.operators and context.matched_agent:
        op_policy = config.operators.get(context.matched_agent.operator)
        if op_policy:
            result = _apply_agent_policy(op_policy, path, allow_patterns)
            if result:
                return result

    # 2. Per-category overrides
    if config.agent_types and context.agent_category:
        cat_policy = config.agent_types.get(context.agent_category)
        if cat_policy:
            result = _apply_agent_policy(cat_policy, path, allow_patterns)
            if result:
                return result

    # 3. Suspected-agent policy
    if context.tier == "suspected-agent":
        sus_policy = config.agent_types.get("suspected-agent") if config.agent_types else None
        if sus_policy:
            result = _apply_agent_policy(sus_policy, path, allow_patterns)
            if result:
                return result

    # 4. Route-level deny rules
    deny_patterns = config.deny or []
    if deny_patterns and any(fnmatch.fnmatch(path, p) for p in deny_patterns):
        if allow_patterns and any(fnmatch.fnmatch(path, p) for p in allow_patterns):
            return _ALLOW
        return _deny(f'Path "{path}" matches deny pattern')

    return _ALLOW


def generate_robots_txt_ai_section(config: AccessConfig) -> str:
    """Generate the AI/agent section of robots.txt from config."""
    lines = [
        "# AI Agent Access Control — generated by agentfriendly",
        "# Modify these rules via access.agent_types in AgentFriendlyConfig",
        "",
    ]

    for category, policy in (config.agent_types or {}).items():
        reps = CATEGORY_UA_REPRESENTATIVES.get(str(category), [])
        if not reps:
            continue

        lines.append(f"# {category} — policy: {policy}")
        for ua in reps:
            lines.append(f"User-agent: {ua}")

        if policy == "deny-all":
            lines.append("Disallow: /")
        elif policy == "allow-public":
            denied = [p for p in (config.deny or []) if "*" not in p]
            for path in denied:
                lines.append(f"Disallow: {path}")
            if not denied:
                lines.append("Allow: /")
        else:
            lines.append("Allow: /")

        lines.append("")

    return "\n".join(lines)
